# coding: utf-8

"""
    Sherpa API

    Sherpa API  # noqa: E501

    The version of the OpenAPI document: delivered
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sherpa.configuration import Configuration


class Size(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'tenure': 'str',
        'duration': 'int',
        'regions': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'tenure': 'tenure',
        'duration': 'duration',
        'regions': 'regions'
    }

    def __init__(self, id=None, name=None, description=None, tenure=None, duration=None, regions=None, local_vars_configuration=None):  # noqa: E501
        """Size - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._description = None
        self._tenure = None
        self._duration = None
        self._regions = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if tenure is not None:
            self.tenure = tenure
        if duration is not None:
            self.duration = duration
        if regions is not None:
            self.regions = regions

    @property
    def id(self):
        """Gets the id of this Size.  # noqa: E501


        :return: The id of this Size.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Size.


        :param id: The id of this Size.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Size.  # noqa: E501


        :return: The name of this Size.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Size.


        :param name: The name of this Size.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Size.  # noqa: E501


        :return: The description of this Size.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Size.


        :param description: The description of this Size.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def tenure(self):
        """Gets the tenure of this Size.  # noqa: E501


        :return: The tenure of this Size.  # noqa: E501
        :rtype: str
        """
        return self._tenure

    @tenure.setter
    def tenure(self, tenure):
        """Sets the tenure of this Size.


        :param tenure: The tenure of this Size.  # noqa: E501
        :type tenure: str
        """

        self._tenure = tenure

    @property
    def duration(self):
        """Gets the duration of this Size.  # noqa: E501


        :return: The duration of this Size.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Size.


        :param duration: The duration of this Size.  # noqa: E501
        :type duration: int
        """

        self._duration = duration

    @property
    def regions(self):
        """Gets the regions of this Size.  # noqa: E501


        :return: The regions of this Size.  # noqa: E501
        :rtype: list[str]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this Size.


        :param regions: The regions of this Size.  # noqa: E501
        :type regions: list[str]
        """

        self._regions = regions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Size):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Size):
            return True

        return self.to_dict() != other.to_dict()
